Module4 task3
htmlacademy-adaptive/1635751-sedona-22 pull request #12
Opened 2021-04-24 21:43 UTC by NikitaShakhovich

Выполнена адаптивная сетка для страницы каталога

2021-04-25 22:36 UTC, pndparade requested changes

2021-04-25 22:36 UTC, pndparade commented on source/catalog.html
>            <div class="video-block__range">
А почему блок управления выше чем картинка? Не доделано ещё?

2021-04-25 22:36 UTC, pndparade commented on source/sass/blocks/gallery.scss
> +    width: 314px;
А зачем зачем здесь 2 параметра ширины?

2021-04-25 22:36 UTC, pndparade commented on source/sass/blocks/gallery.scss
> +    max-width: 400px;
Такой же вопрос

2021-04-26 05:47 UTC, NikitaShakhovich commented on source/catalog.html
>            <div class="video-block__range">
Да, еще не доделал. В module5вместе с кнопками буду позиционировать.

2021-04-26 05:47 UTC, NikitaShakhovich commented on source/sass/blocks/gallery.scss
> +    width: 314px;
У меня из-за вертикального скрола (он занимает примерно 15px) переносятся блоки. Допустим при ширине вьюпорта 1215px им не хватало места и они переносились, хотя должны били при 1999px. Таким способом исправил этот момент.

2021-04-26 07:01 UTC, merged